#include "GainPatch.hpp"
#include "SimpleDelayPatch.hpp"
#include "ParametricEqPatch.hpp"
#include "OverdrivePatch.hpp"
#include "PhaserPatch.hpp"
#include "StateVariableFilterPatch.hpp"
#include "ResonantFilterPatch.hpp"
#include "LeakyIntegratorPatch.hpp"
#include "FreeVerbPatch.hpp"
#include "OctaveDownPatch.hpp"
#include "StereoMixerPatch.hpp"
#include "VibroFlangePatch.hpp"
#include "RingModulatorPatch.hpp"
#include "SynthPatch.hpp"
#include "FourBandsEqPatch.hpp"
#include "Contest/BiasedDelayPatch.hpp"
#include "Contest/blo_bleep.hpp"
#include "Contest/BiasPatch.hpp"
#include "Contest/BitH8rPatch.hpp"
#include "Contest/ConnyPatch.hpp"
#include "Contest/DroneBox.hpp"
#include "Contest/DualTremoloPatch.hpp"
#include "mdaPorts/MdaBandistoPatch.cpp"
#include "mdaPorts/MdaStereoPatch.cpp"
#include "mdaPorts/MdaTransientPatch.cpp"
#include "Qompression.hpp"
#include "PsycheFilter.hpp"
#include "ChorusPatch.hpp"
#include "TremoloPatch.hpp"
#include "DigitalMayhemPatch.hpp"
#include "ReverseReverbPatch.hpp"
#include "SimpleDistortionPatch.hpp"
#include "MoogPatch.hpp"
#include "KarplusStrongPatch.hpp"
#include "Faust/FaustVerbPatch.hpp"
#include "Faust/HarpPatch.hpp"
#include "Faust/HarpAutoPatch.hpp"
#include "Faust/EchoPatch.hpp"
#include "Faust/SmoothDelayPatch.hpp"
#include "Faust/StereoEchoPatch.hpp"
#include "Faust/CrybabyPatch.hpp"
#include "Faust/StereoWahPatch.hpp"
#include "Faust/LowPassFilterPatch.hpp"
#include "Faust/LowShelfPatch.hpp"
#include "Faust/PitchShifterPatch.hpp"

// #include "Faust/AutoWahPatch.hpp"
// #include "Faust/QompanderPatch.hpp"

#include "Guitarix/GuitarixMoogPatch.hpp"
#include "Guitarix/GuitarixOverdrivePatch.hpp"
#include "Guitarix/GuitarixPhaserMonoPatch.hpp"
#include "Guitarix/GuitarixOscTubePatch.hpp"
#include "Guitarix/GuitarixFlangerGXPatch.hpp"
#include "Guitarix/GuitarixDunwahPatch.hpp"
#include "Guitarix/GuitarixTonePatch.hpp"
#include "Guitarix/GuitarixBMfpPatch.hpp"
#include "Guitarix/GuitarixDistortion1Patch.hpp"

// #include "JotReverbPatch.hpp" // bug fix to be done re. new firmware
// #include "SimpleDriveDelayPatch.hpp"
// #include "Autotalent/AutotalentPatch.hpp"
// #include "TemplatePatch.hpp"
// #include "EnvelopeFilterPatch.hpp" /* too cpu intensive (sqrt...) */
// #include "TemplatePatch.hpp"
// #include "Contest/JumpDelay.hpp" /* uses calloc and free */
// #include "Contest/SampleJitterPatch.hpp" /* requires juce::Random */
// #include "Contest/SirenPatch.hpp" /* causes assert_failed in DMA_GetFlagStatus() */
// #include "LpfDelayPatch.hpp" /* not compatible with Windows yet */
// #include "LpfDelayPhaserPatch.hpp" /* not compatible with Windows yet */
// #include "WaveshaperPatch.hpp" /* not compatible with Windows yet */
// #include "TestTonePatch.hpp"
// #include "FlangerPatch.hpp"
