  REGISTER_PATCH(GainPatch, "Gain");
  // REGISTER_PATCH(TemplatePatch, "Template");
  REGISTER_PATCH(SimpleDelayPatch, "Simple Delay");
  REGISTER_PATCH(ParametricEqPatch, "Parametric EQ");
  REGISTER_PATCH(OverdrivePatch, "Overdrive");
  REGISTER_PATCH(PhaserPatch, "Phaser");
  REGISTER_PATCH(StateVariableFilterPatch, "State Variable Filter");
  REGISTER_PATCH(ResonantFilterPatch, "Resonant Low Pass Filter");
//  REGISTER_PATCH(FlangerPatch, "Flanger");
  REGISTER_PATCH(LeakyIntegratorPatch, "Leaky Integrator");
  REGISTER_PATCH(LpfDelayPatch, "Low Pass Filtered Delay");
  REGISTER_PATCH(LpfDelayPhaserPatch, "Low Pass Filtered Delay with Phaser");
  REGISTER_PATCH(WaveshaperPatch, "Waveshaper");
  REGISTER_PATCH(FreeVerbPatch, "FreeVerb");
  REGISTER_PATCH(OctaveDownPatch, "Octave Pitch Shifter");
  // REGISTER_PATCH(TestTonePatch, "Test Tone");
  REGISTER_PATCH(StereoMixerPatch, "Stereo Mixer");
  REGISTER_PATCH(VibroFlangePatch, "Vibro-Flange");
  REGISTER_PATCH(RingModulatorPatch, "Ring Modulator");
  REGISTER_PATCH(FourBandsEqPatch, "FourBandsEqPatch");
  REGISTER_PATCH(EnvelopeFilterPatch, "Envelope Filter");
  REGISTER_PATCH(JotReverbPatch,"JotReverbPatch");
//   REGISTER_PATCH(HighPassFilterPatch, "a High Pass Filter");
  REGISTER_PATCH(BiasedDelayPatch, "Contest/BiasedDelayPatch");
//   REGISTER_PATCH(JumpDelay, "Contest/JumpDelay");
//   REGISTER_PATCH(SampleJitterPatch, "Contest/SampleJitterPatch");
//   REGISTER_PATCH(SirenPatch, "Contest/SirenPatch");
  REGISTER_PATCH(little_blo_bleep, "Contest/blo bleep");
  REGISTER_PATCH(BiasPatch, "Contest/Bias");
  REGISTER_PATCH(BitH8rPatch, "Contest/BitH8r");
  REGISTER_PATCH(ConnyPatch, "Contest/ConnyPatch");
  REGISTER_PATCH(DroneBoxPatch, "Contest/DroneBox");
  REGISTER_PATCH(DualTremoloPatch, "Contest/DualTremolo");
  REGISTER_PATCH(MdaBandistoPatch, "mdaPorts/MdaBandisto");
  REGISTER_PATCH(MdaStereoPatch, "mdaPorts/MdaStereo");
  REGISTER_PATCH(MdaTransientPatch, "mdaPorts/MdaTransient");
